---
version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:$CP_IMAGE_TAG
    hostname: zookeeper
    labels:
      io.astronomer.docker: "true"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:$CP_IMAGE_TAG
    hostname: kafka
    labels:
      io.astronomer.docker: "true"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  event-api:
    image: astronomerinc/ap-event-api:$CLICKSTREAM_IMAGE_TAG
    labels:
      io.astronomer.docker: "true"
    depends_on:
      - kafka
    environment:
      EA_API_PORT: 8080
      EA_ADMIN_PORT: 8081
      EA_DEBUG_MODE: 'true'
      EA_ENABLE_PPROF: 'true'
      EA_ENABLE_HEALTH_CHECK: 'true'
      EA_ENABLE_PROMETHEUS: 'true'
      EA_KAFKA_BROKERS: 'kafka:9092'
      EA_KAFKA_TOPIC: 'main'
    ports:
      - "8080:8080"
      - "8081:8081"

  event-router:
    image: astronomerinc/ap-event-router:$CLICKSTREAM_IMAGE_TAG
    labels:
      io.astronomer.docker: "true"
    entrypoint: event-router mock --disable-sse "S3 Event Logs:s3-event-logs"
    environment:
      ER_KAFKA_INGESTION_TOPIC: astro-main
      ER_KAFKA_GROUP_ID: event-router
      ER_KAFKA_RETRY_TOPIC: retry
      ER_KAFKA_BROKERS: kafka:9092
      ER_DEBUG: 'true'
      ER_SERVE_PORT: 9091
      ER_TOPIC: main
      ER_GROUP_ID: moc
      ER_SSE_URL: http://localhost
      ER_SSE_AUTH: auth
    depends_on:
      - kafka
    ports:
      - "9091:9091"
    volumes:
      - config.yml:/etc/astronomer/clickstream/config.yml

  event-forwarder-ga:
    image: astronomerinc/ap-event-forwarder:$CLICKSTREAM_IMAGE_TAG
    labels:
      io.astronomer.docker: "true"
    environment:
      EF_INTEGRATION: google-analytics
      EF_KAFKA_INGESTION_TOPIC: astro-google-analytics
      EF_KAFKA_GROUP_ID: iw-google-analytics
      EF_KAFKA_RETRY_TOPIC: retry
      EF_KAFKA_BROKERS: kafka:9092
      EF_DEBUG: 'true'
      EF_SERVE_PORT: 9091
      EF_TOPIC: main
      EF_GROUP_ID: moc
      EF_SSE_URL: http://localhost
      EF_SSE_AUTH: auth
    depends_on:
      - kafka
    ports:
      - "9091:9091"
    volumes:
      - config.yml:/etc/astronomer/clickstream/config.yml
