---
version: "2"
services:
  zookeeper:
    image: astronomerio/zookeeper:latest
    hostname: zookeeper
    labels:
      io.astronomer.docker: "true"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: astronomerio/kafka:latest
    hostname: kafka
    labels:
      io.astronomer.docker: "true"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  event-api:
    image: astronomerinc/ap-event-api:latest
    labels:
      io.astronomer.docker: "true"
    depends_on:
      - kafka
    environment:
      INGESTION_API_PORT: 8080
      INGESTION_ADMIN_PORT: 8081
      INGESTION_DEBUG_MODE: 'true'
      INGESTION_ENABLE_PPROF: 'true'
      INGESTION_ENABLE_HEALTH_CHECK: 'true'
      INGESTION_ENABLE_PROMETHEUS: 'true'
      INGESTION_KAFKA_BROKERS: 'kafka:9092'
      INGESTION_KAFKA_TOPIC: 'main'
    ports:
      - "8080:8080"
      - "8081:8081"

  event-router:
    image: astronomerinc/ap-event-router:latest
    labels:
      io.astronomer.docker: "true"
    entrypoint: event-router mock --disable-sse "S3 Event Logs:s3-event-logs"
    environment:
      ER_KAFKA_INGESTION_TOPIC: main
      ER_KAFKA_GROUP_ID: event-router
      ER_KAFKA_RETRY_TOPIC: retry
      ER_KAFKA_BROKERS: kafka:9092
      ER_HOUSTON_API_URL: localhost
      ER_HOUSTON_API_KEY: key
      ER_DEBUG: 'true'
      ER_SERVE_PORT: 9091
      ER_TOPIC: main
      ER_GROUP_ID: moc
      ER_SSE_URL: http://localhost
      ER_SSE_AUTH: auth
    depends_on:
      - kafka
    ports:
      - "9091:9091"

  #   jmx-exporter:
  #       image: "sscaling/jmx-prometheus-exporter"
  #       ports:
  #           - "5556:5556"
  #       volumes:
  #           - ./configs/jmx-exporter.yml:/opt/jmx_exporter/config.yml
  #       depends_on:
  #           - "kafka"

  #   prometheus:
  #       image: "prom/prometheus"
  #       ports:
  #           - "9090:9090"
  #       volumes:
  #           - ./configs/prom.yml:/prom.yml
  #       command:
  #           - "-config.file=/prom.yml"
  #       depends_on:
  #           - "kafka"
